remote_theme: fongandrew/hydeout

# Setup
title:            Yulim Lee
tagline:          ?testing? # i have no idea where this pops up
description:      My Engineering Portfolio

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
sidebar_home_link:  true  #this creates a HOME sidebar link that goes back to the main/home page aka Index

#sidebar icon link 
github_username: 96yrlee
linkedin_username: yulim-lee-24b227131





